[package]
name = "qcpt"
description = "QCP transport low-level utility"
edition.workspace = true
authors.workspace = true
version.workspace = true
license.workspace = true
rust-version = "1.74.0"

[dependencies]
anstyle = "1.0.8"
anyhow = { workspace = true }
clap = { workspace = true, features = ["wrap_help", "derive", "cargo", "help"] }
gethostname = "0.5.0"
rcgen = { version = "0.13", features = ["crypto", "ring"], default-features = false }
rustls-pki-types = "1.8.0"
#quinn = { workspace = true }

[build-dependencies]
built = { version = "0.7.4", features = ["git2"] }
