.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH qcp 1  "qcp " 
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH NAME
qcp \- Secure remote file copy utility which uses the QUIC protocol over UDP
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH SYNOPSIS
\fBqcp\fR [\fB\-b\fR|\fB\-\-rx\fR] [\fB\-B\fR|\fB\-\-tx\fR] [\fB\-r\fR|\fB\-\-rtt\fR] [\fB\-\-congestion\fR] [\fB\-\-initial\-congestion\-window\fR] [\fB\-p\fR|\fB\-\-port\fR] [\fB\-t\fR|\fB\-\-timeout\fR] [\fB\-\-address\-family\fR] [\fB\-\-ssh\fR] [\fB\-S \fR] [\fB\-P\fR|\fB\-\-remote\-port\fR] [\fB\-T\fR|\fB\-\-time\-format\fR] [\fB\-\-ssh\-config\fR] [\fB\-\-ssh\-subsystem\fR] [\fB\-\-show\-config\fR] [\fB\-\-config\-files\fR] [\fB\-\-help\-buffers\fR] [\fB\-d\fR|\fB\-\-debug\fR] [\fB\-l\fR|\fB\-\-log\-file\fR] [\fB\-q\fR|\fB\-\-quiet\fR] [\fB\-s\fR|\fB\-\-statistics\fR] [\fB\-\-remote\-debug\fR] [\fB\-\-profile\fR] [\fB\-\-dry\-run\fR] [\fB\-\-remote\-config\fR] [\fB\-4 \fR] [\fB\-6 \fR] [\fB\-h\fR|\fB\-\-help\fR] [\fISOURCE\fR] [\fIDESTINATION\fR] 
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH DESCRIPTION
The QUIC Copier (qcp) is an experimental high\-performance remote file copy utility for long\-distance internet connections. It is intended as a drop\-in replacement for scp.
.PP
qcp offers similar security to scp using existing, well\-known mechanisms, and better throughput on congested networks.
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH USAGE
.TP
.BI "qcp " "[OPTIONS] " "[SOURCE] " [DESTINATION]
e.g.   qcp some/file my\-server:some\-directory/
.PP
Exactly one of source and destination must be remote.
.PP
qcp will read your ssh config file to resolve any host name aliases you may have defined. The idea is, if you can ssh directly to a given host, you should be able to qcp to it by the same name. However, some particularly complicated ssh config files may be too much for qcp to understand. (In particular, Match directives are not currently supported.) In that case, you can use \-\-ssh\-config to provide an alternative configuration (or set it in your qcp configuration file).
.PP
.SS LIMITATIONS
.TP
You must be able to ssh directly to the remote machine, and exchange UDP packets with it on a given port. (If the local machine is behind connection\-tracking NAT, things work just fine. This is the case for the vast majority of home and business network connections.)
.TP
Be aware that network security systems can’t readily identify QUIC traffic as such. It’s opaque, and high bandwidth. Some security systems might flag it as a potential threat.

.SS CAVEATS
.TP
This is an experimental implementation of an experimental protocol. While it has security goals, these have not been verified.
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fISOURCE\fR]
The source file. This may be a local filename, or remote specified as HOST:FILE or USER@HOST:FILE
.TP
[\fIDESTINATION\fR]
Destination. This may be a file or directory. It may be local or remote.

If remote, specify as HOST:DESTINATION or USER@HOST:DESTINATION; or simply HOST: or USER@HOST: to copy to your home directory there.
.SH "NETWORK TUNING"
.TP
\fB\-b\fR, \fB\-\-rx\fR=\fIbytes\fR
The maximum network bandwidth we expect receiving data FROM the remote system. [default: 12.5M]

This parameter is always interpreted as the **local** bandwidth, whether operating in client or server mode.

This may be specified directly as a number, or as an SI quantity like `10M` or `256k`. **Note that this is described in BYTES, not bits**; if (for example) you expect to fill a 1Gbit ethernet connection, 125M might be a suitable setting.
.TP
\fB\-B\fR, \fB\-\-tx\fR=\fIbytes\fR
The maximum network bandwidth we expect sending data TO the remote system, if it is different from the bandwidth FROM the system. (For example, when you are connected via an asymmetric last\-mile DSL or fibre profile.)

This parameter is always interpreted as the **local** bandwidth, whether operating in client or server mode.

If not specified or 0, uses the value of `rx`.
.TP
\fB\-r\fR, \fB\-\-rtt\fR=\fIms\fR
The expected network Round Trip time to the target system, in milliseconds. [default: 300]
.TP
\fB\-\-help\-buffers\fR
Outputs additional information about kernel UDP buffer sizes and platform\-specific tips
.SH "ADVANCED NETWORK TUNING"
.TP
\fB\-\-congestion\fR=\fIalgorithm\fR
Specifies the congestion control algorithm to use. [default: cubic]
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
cubic: The congestion algorithm TCP uses. This is good for most cases
.IP \(bu 2
bbr: (Use with caution!) An experimental algorithm created by Google, which increases goodput in some situations (particularly long and fat connections where the intervening buffers are shallow). However this comes at the cost of having more data in\-flight, and much greater packet retransmission. See `https://blog.apnic.net/2020/01/10/when\-to\-use\-and\-not\-use\-bbr/` for more discussion
.RE
.TP
\fB\-\-initial\-congestion\-window\fR=\fIbytes\fR
_(Network wizards only!)_ The initial value for the sending congestion control window, in bytes. If unspecified, the active congestion control algorithm decides.

This may be specified directly as a number, or as an SI quantity like `10k`.

_Setting this value too high reduces performance!_
.SH CONNECTION
.TP
\fB\-p\fR, \fB\-\-port\fR=\fIM\-N\fR
Uses the given UDP port or range on the **local** endpoint. This can be useful when there is a firewall between the endpoints.

For example: `12345`, `20000\-20100`

If unspecified, uses any available UDP port.
.TP
\fB\-t\fR, \fB\-\-timeout\fR=\fIsec\fR
Connection timeout for the QUIC endpoints [seconds; default 5]

This needs to be long enough for your network connection, but short enough to provide a timely indication that UDP may be blocked.
.TP
\fB\-\-address\-family\fR=\fIADDRESS_FAMILY\fR
Forces use of a particular IP version when connecting to the remote. [default: any]
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
inet: IPv4
.IP \(bu 2
inet6: IPv6
.IP \(bu 2
any: Unspecified. qcp will use whatever seems suitable given the target address or the result of DNS lookup
.RE
.TP
\fB\-\-ssh\fR=\fISSH\fR
Specifies the ssh client program to use [default: `ssh`]
.TP
\fB\-S\fR=\fIssh\-option\fR
Provides an additional option or argument to pass to the ssh client. [default: none]

**On the command line** you must repeat `\-S` for each argument. For example, to pass `\-i /dev/null` to ssh, specify: `\-S \-i \-S /dev/null`
.TP
\fB\-P\fR, \fB\-\-remote\-port\fR=\fIM\-N\fR
Uses the given UDP port or range on the **remote** endpoint. This can be useful when there is a firewall between the endpoints.

For example: `12345`, `20000\-20100`

If unspecified, uses any available UDP port.
.TP
\fB\-\-ssh\-config\fR=\fIFILE\fR
Alternative ssh config file(s)

By default, qcp reads your user and system ssh config files to look for Hostname aliases. In some cases the logic in qcp may not read them successfully; this is an escape hatch, allowing you to specify one or more alternative files to read instead (which may be empty, nonexistent or /dev/null).

This option is really intended to be used in a qcp configuration file. On the command line, you can repeat `\-\-ssh\-config file` as many times as needed.
.TP
\fB\-\-ssh\-subsystem\fR
Ssh subsystem mode

This mode causes qcp to run `ssh <host> \-s qcp` instead of `ssh <host> qcp \-\-server`. This is useful where the remote system has a locked\-down `PATH` and the qcp binary is not resident on that `PATH`.

The remote system sshd has to be configured with a line like this:

`Subsystem qcp /usr/local/bin/qcp \-\-server`
.TP
\fB\-4\fR
Forces use of IPv4

This is a convenience alias for `\-\-address\-family inet`
.TP
\fB\-6\fR
Forces use of IPv6

This is a convenience alias for `\-\-address\-family inet6`
.SH OUTPUT
.TP
\fB\-T\fR, \fB\-\-time\-format\fR=\fIFORMAT\fR
Specifies the time format to use when printing messages to the console or to file [default: local]
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
local: Local time (as best as we can figure it out), as "year\-month\-day HH:MM:SS"
.IP \(bu 2
utc: UTC time, as "year\-month\-day HH:MM:SS"
.IP \(bu 2
rfc3339: UTC time, in the format described in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339)
.RE
.TP
\fB\-l\fR, \fB\-\-log\-file\fR=\fIFILE\fR
Log to a file

By default the log receives everything printed to stderr. To override this behaviour, set the environment variable `RUST_LOG_FILE_DETAIL` (same semantics as `RUST_LOG`).
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Quiet mode

Switches off progress display and statistics; reports only errors
.TP
\fB\-s\fR, \fB\-\-statistics\fR
Show additional transfer statistics
.TP
\fB\-\-profile\fR
Output timing profile data after completion
.SH CONFIGURATION
.TP
\fB\-\-show\-config\fR
Outputs the local configuration, then exits.

If a remote `SOURCE` or `DESTINATION` argument is given, outputs the configuration we would use for operations to that host.

If not, outputs only global settings from configuration, which may be overridden by `Host` blocks in configuration files.
.TP
\fB\-\-config\-files\fR
Outputs the paths to configuration file(s), then exits
.TP
\fB\-\-dry\-run\fR
Connects to a remote server but does not actually transfer any files. This is useful to test that the control channel works and when debugging the negotiated bandwidth parameters (see also `\-\-remote\-config`)
.TP
\fB\-\-remote\-config\fR
Outputs the server\*(Aqs configuration for this connection. (Unlike `\-\-show\-config`, this option does not prevent a file transfer. However, you can do so by selecting `\-\-dry\-run` mode.)

The output shows both the server\*(Aqs _static_ configuration (by reading config files) and its _final_ configuration (taking account of the client\*(Aqs expressed preferences).
.SH DEBUG
.TP
\fB\-d\fR, \fB\-\-debug\fR
Enable detailed debug output

This has the same effect as setting `RUST_LOG=qcp=debug` in the environment. If present, `RUST_LOG` overrides this option.
.TP
\fB\-\-remote\-debug\fR
Enables detailed debug output from the remote endpoint (this may interfere with transfer speeds)
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH "EXIT STATUS"
.TP
The qcp utility exits 0 on success, and >0 if an error occurs.
.SH "NETWORK PROTOCOL"
.TP
qcp is a \fIhybrid\fR protocol. We use \fIssh\fR to establish a control channel and exchange ephemeral TLS certificates, then a \fIQUIC\fR connection to transport data.
.TP
Detailed protocol documentation can be found at
.UR https://docs.rs/qcp/latest/qcp/protocol/
.UE
.SS "PERFORMANCE TUNING"
See
.UR https://docs.rs/qcp/latest/qcp/doc/performance/
.UE
.SS TROUBLESHOOTING
See
.UR https://docs.rs/qcp/latest/qcp/doc/troubleshooting/
.UE
.SH BUGS
.TP
Please report any you find via the issue tracker: 
.UR https://github.com/crazyscot/qcp/issues
.UE
.SH "SEE ALSO"
.TP
.BR "ssh(1), " "ssh_config(5), " "RFC 4254, " "RFC 9000, " "RFC 9001"
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.SH AUTHORS
Ross Younger <qcp@crazyscot.com>
