[target.'cfg(target_os="linux")']
# using mold breaks cargo cross on musl (the image is based on focal, which does not have a mold package)
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.'cfg(target_os="windows")']
rustflags = ["-C", "link-arg=-fuse-ld=lld"] 

# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
