#!/bin/sh -e
# args: [--release|--no-release] [<rust-target>]
# prerequisites:
#   cargo build --release
#   cargo xtask licenses -o qcp/misc/licenses.html

TARGET=$2
if [ -z "$TARGET" ]; then
  echo NOTE: no target specified, assuming native build
  TARGETOPT=
else
  TARGETOPT="--target ${TARGET}"
fi

RELEASE_TYPE=$1
case "$RELEASE_TYPE" in
  --release)
      REVISION= ;;
  *)
      GITHASH=$(git rev-parse --short=8 HEAD)
      REVISION="g${GITHASH}" ;;
esac

set -x

gzip -9n < CHANGELOG.md > qcp/misc/changelog.gz

cargo xtask dch -p qcp
gzip -9n < qcp/debian/changelog > qcp/debian/changelog.Debian.gz
gzip -9n < qcp/qcp.cdx.xml > qcp/qcp.cdx.xml.gz

output=$(cargo deb -p qcp --no-build --locked ${TARGETOPT} --deb-revision "${REVISION}")
: $output

set +x

# Strip warnings; the deb is the last "word" printed
DEB=$(echo ${output} | sed 's/.* //g')

if [ -z "$GITHUB_ENV" ]; then
  echo "Would write to GITHUB_ENV: BUILT_DEB_FILE=${DEB}"
else
  echo "BUILT_DEB_FILE=${DEB}" >> "$GITHUB_ENV"
fi
