name: cleanup caches made by a branch
on:
  pull_request:
    types:
      - closed
  delete:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      # `actions:write` permission is required to delete caches
      #   See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
      contents: read
    steps:
      - name: Clean up on PR merge
        uses: snnaplab/delete-branch-cache-action@265e9b3b5659990e97d080edf523c755739aa938 # v1.0.0
        with:
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.number }}/merge
        if: github.event_name == 'pull_request'
        # and only when a PR is closed; that's done for us by the 'on' clause above
      - name: Clean up on workflow dispatch
        uses: snnaplab/delete-branch-cache-action@265e9b3b5659990e97d080edf523c755739aa938 # v1.0.0
        with:
          ref: refs/heads/${{ github.ref_name }}
        if: github.event_name == 'workflow_dispatch'
      - name: Clean up on branch delete
        uses: snnaplab/delete-branch-cache-action@265e9b3b5659990e97d080edf523c755739aa938 # v1.0.0
        with:
          ref: refs/heads/${{ github.event.ref }}
        if: github.event_name == 'delete' && github.ref_type == 'branch'
