name: cleanup caches made by a branch
on:
  pull_request:
    types:
      - closed
  delete:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      # `actions:write` permission is required to delete caches
      #   See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
      contents: read
    steps:
      - uses: snnaplab/delete-branch-cache-action@v1.0.0
        with:
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.number }}/merge
        if: github.event_name == 'closed'
      - uses: snnaplab/delete-branch-cache-action@v1.0.0
        with:
          ref: refs/heads/${{ github.ref_name }}
        if: github.event_name == 'delete' || github.event_name == 'workflow_dispatch'
